[package]
name = "my-alife"
version = "0.1.0"
authors = ["Koji Ota <afterjnih@gmail.com>"]

[dependencies]
glutin = "*"
gl = "0.10.0"
glium = "0.20.0"
ndarray = "0.11.0"
ndarray-rand = "0.7.0"
rand = "0.4.1"
